import PySide6.QtCore as QtC
import PySide6.QtWidgets as QtW
import PySide6.QtGui as QtG


# LOCALE
LOCALE = QtC.QLocale(QtC.QLocale.Language.English, QtC.QLocale.Country.UnitedStates)

# ALIGNMENT FLAGS
LEFT_ALIGN = QtC.Qt.AlignmentFlag.AlignLeft
RIGHT_ALIGN = QtC.Qt.AlignmentFlag.AlignRight
CENTER_ALIGN = QtC.Qt.AlignmentFlag.AlignCenter
TOP_ALIGN = QtC.Qt.AlignmentFlag.AlignTop
VERT_CENTER_ALIGN = QtC.Qt.AlignmentFlag.AlignVCenter

# SIZE POLICIES
FIXED_SIZE = QtW.QSizePolicy.Policy.Fixed
EXPANDING_SIZE = QtW.QSizePolicy.Policy.Expanding
MINIMUM_SIZE = QtW.QSizePolicy.Policy.Minimum
PREFERRED_SIZE = QtW.QSizePolicy.Policy.Preferred

# COMMONS
DEFAULT_BUTTON_MIN_SIZE = QtC.QSize(100, 0)
DEFAULT_MARGINS = QtC.QMargins(0, 0, 0, 0)
DATEBOX_SIZE_POLICY = QtW.QSizePolicy(EXPANDING_SIZE, FIXED_SIZE)
DATEBOX_FORMAT = "MMM dd hh:mm:ss"
DEFAULT_LABEL_MIN_SIZE = QtC.QSize(60, 0)
DEFAULT_LABEL_ALIGNMENT = RIGHT_ALIGN | VERT_CENTER_ALIGN
DEFAULT_TEXTBOX_READ_ONLY = True
NAV_BUTTON_ENABLED = False



# WINDOW
WINDOW_TITLE = 'Log browser'
WINDOW_SIZE = QtC.QSize(800, 600)
# MAIN LAYOUT
MAIN_LAYOUT_SPACING = 15
MAIN_LAYOUT_MARGINS = QtC.QMargins(20, 15, 20, 15)
# SPLITTER
SPLITTER_COLLAPSIBLE = False

# FILE PATH TEXTBOX
FILE_PATH_TEXTBOX_READ_ONLY = DEFAULT_TEXTBOX_READ_ONLY
# OPEN BUTTON
OPEN_BUTTON_LABEL = 'Open'
OPEN_BUTTON_MIN_SIZE = DEFAULT_BUTTON_MIN_SIZE


# LEFT LAYOUT
LEFT_LAYOUT_MARGINS = DEFAULT_MARGINS
# DATE FILTER LAYOUT
DATE_SPACER_WIDTH = 20
DATE_SPACER_HEIGHT = 20
DATE_SPACER_HORIZONTAL_SIZE_POLICY = FIXED_SIZE
DATE_SPACER_VERTICAL_SIZE_POLICY = MINIMUM_SIZE
# DATE FROM FILTER
DATE_FROM_LABEL = 'From'
DATE_FROM_DATEBOX_SIZE_POLICY = DATEBOX_SIZE_POLICY
DATE_FROM_DATEBOX_DEFAULT_DATETIME = QtC.QDateTime(QtC.QDate(2023, 12, 10), QtC.QTime(0, 0, 0))
DATE_FROM_DATEBOX_FORMAT = DATEBOX_FORMAT
# DATE TO FILTER
DATE_TO_LABEL = 'To'
DATE_TO_DATEBOX_SIZE_POLICY = DATEBOX_SIZE_POLICY
DATE_TO_DATEBOX_DEFAULT_DATETIME = QtC.QDateTime(QtC.QDate(2023, 12, 10), QtC.QTime(23, 59, 59))
DATE_TO_DATEBOX_FORMAT = DATEBOX_FORMAT
# FILTER BUTTONS
FILTER_BUTTON_LABEL = 'Filter'
RESET_BUTTON_LABEL = 'Reset'


# RIGHT LAYOUT
RIGHT_LAYOUT_MARGINS = DEFAULT_MARGINS
# DETAILS LABEL
DETAILS_LABEL = 'Log details'
DETAILS_LABEL_MIN_SIZE = QtC.QSize(225, 20)
DETAILS_LABEL_SIZE_POLICY = QtW.QSizePolicy(PREFERRED_SIZE, FIXED_SIZE)
DETAILS_LABEL_ALIGNMENT = CENTER_ALIGN
(DETAILS_LABEL_BOLD_FONT := QtG.QFont()).setBold(True)
# DATE
DATE_LABEL = 'Date'
DATE_LABEL_MIN_SIZE = DEFAULT_LABEL_MIN_SIZE
DATE_LABEL_ALIGNMENT = DEFAULT_LABEL_ALIGNMENT
DATE_TEXTBOX_READ_ONLY = DEFAULT_TEXTBOX_READ_ONLY
# TIME
TIME_LABEL = 'Time'
TIME_LABEL_MIN_SIZE = DEFAULT_LABEL_MIN_SIZE
TIME_LABEL_ALIGNMENT = DEFAULT_LABEL_ALIGNMENT
TIME_TEXTBOX_READ_ONLY = DEFAULT_TEXTBOX_READ_ONLY
# HOSTNAME
HOSTNAME_LABEL = 'Hostname'
HOSTNAME_LABEL_MIN_SIZE = DEFAULT_LABEL_MIN_SIZE
HOSTNAME_LABEL_ALIGNMENT = DEFAULT_LABEL_ALIGNMENT
HOSTNAME_TEXTBOX_READ_ONLY = DEFAULT_TEXTBOX_READ_ONLY
# PROCESS ID
PROCESS_ID_LABEL = 'Process ID'
PROCESS_ID_LABEL_MIN_SIZE = DEFAULT_LABEL_MIN_SIZE
PROCESS_ID_LABEL_ALIGNMENT = DEFAULT_LABEL_ALIGNMENT
PROCESS_ID_TEXTBOX_READ_ONLY = DEFAULT_TEXTBOX_READ_ONLY
# IP ADDRESS
IP_ADDRESS_LABEL = 'IP Address'
IP_ADDRESS_LABEL_MIN_SIZE = DEFAULT_LABEL_MIN_SIZE
IP_ADDRESS_LABEL_ALIGNMENT = DEFAULT_LABEL_ALIGNMENT
IP_ADDRESS_TEXTBOX_READ_ONLY = DEFAULT_TEXTBOX_READ_ONLY
# USERNAME
USERNAME_LABEL = 'Username'
USERNAME_LABEL_MIN_SIZE = DEFAULT_LABEL_MIN_SIZE
USERNAME_LABEL_ALIGNMENT = DEFAULT_LABEL_ALIGNMENT
USERNAME_TEXTBOX_READ_ONLY = DEFAULT_TEXTBOX_READ_ONLY
# CATEGORY
CATEGORY_LABEL = 'Category'
CATEGORY_LABEL_MIN_SIZE = DEFAULT_LABEL_MIN_SIZE
CATEGORY_LABEL_ALIGNMENT = DEFAULT_LABEL_ALIGNMENT
CATEGORY_TEXTBOX_READ_ONLY = DEFAULT_TEXTBOX_READ_ONLY
# MESSAGE
MESSAGE_LABEL = 'Message'
MESSAGE_LABEL_MIN_SIZE = DEFAULT_LABEL_MIN_SIZE
MESSAGE_LABEL_ALIGNMENT = RIGHT_ALIGN | TOP_ALIGN
MESSAGE_TEXTBOX_MAX_SIZE = QtC.QSize(16777215, 100)
MESSAGE_TEXTBOX_READ_ONLY = DEFAULT_TEXTBOX_READ_ONLY
# SIZE
SIZE_LABEL = 'Size'
SIZE_LABEL_MIN_SIZE = DEFAULT_LABEL_MIN_SIZE
SIZE_LABEL_ALIGNMENT = DEFAULT_LABEL_ALIGNMENT
SIZE_TEXTBOX_READ_ONLY = DEFAULT_TEXTBOX_READ_ONLY


# PREVIOUS BUTTON
PREVIOUS_BUTTON_LABEL = 'Previous'
PREVIOUS_BUTTON_MIN_SIZE = DEFAULT_BUTTON_MIN_SIZE
PREVIOUS_BUTTON_LABEL_ALIGNMENT = LEFT_ALIGN
PREVIOUS_BUTTON_ENABLED = NAV_BUTTON_ENABLED
# DARK THEME BUTTON
DARK_THEME_BUTTON_LABEL = 'Dark theme'
DARK_THEME_BUTTON_ALIGNMENT = CENTER_ALIGN
# NEXT BUTTON
NEXT_BUTTON_LABEL = 'Next'
NEXT_BUTTON_MIN_SIZE = DEFAULT_BUTTON_MIN_SIZE
NEXT_BUTTON_LABEL_ALIGNMENT = RIGHT_ALIGN
NEXT_BUTTON_ENABLED = NAV_BUTTON_ENABLED


# OPEN LOG FILE DIALOG
OPEN_LOG_FILE_DIALOG_TITLE = 'Open log file'
OPEN_LOG_FILE_DIALOG_DIRECTORY = ''
OPEN_LOG_FILE_DIALOG_FILTER = 'Log files (*.log)'


# LOG DETAILS CONSTANTS
DATETIME_DATE_FORMAT = '%b %d'
DATETIME_TIME_FORMAT = '%H:%M:%S'
NOT_AVAILABLE_MESSAGE = 'N/A'